/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: f8b6f3914b74327108ff14e53f9acc3e)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	ASSET_BUCKET: R2Bucket;
	OMS_DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	PUBLIC_SITE_NAME: string;
	PUBLIC_SITE_URL: string;
	PUBLIC_SITE_DESCRIPTION: string;
	PUBLIC_SITE_TAGLINE: string;
	PUBLIC_ADMIN_NAME: string;
	PUBLIC_EMBED_ALLOWED_ORIGINS: string;
	PUBLIC_SITE_LOGO: string;
	PUBLIC_SITE_THEME_COLOR: string;
	PUBLIC_SITE_LOCALE: string;
	PUBLIC_STOREFRONT_TEMPLATE: string;
	AUTH_SECRET: string;
	INSTALL_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_NAME" | "PUBLIC_SITE_URL" | "PUBLIC_SITE_DESCRIPTION" | "PUBLIC_SITE_TAGLINE" | "PUBLIC_ADMIN_NAME" | "PUBLIC_EMBED_ALLOWED_ORIGINS" | "PUBLIC_SITE_LOGO" | "PUBLIC_SITE_THEME_COLOR" | "PUBLIC_SITE_LOCALE" | "PUBLIC_STOREFRONT_TEMPLATE" | "AUTH_SECRET" | "INSTALL_TOKEN">> {}
}
